/**** Data Model Schema *************/

const mongoose = require('mongoose');
const Schema = mongoose.Schema;


const data_model_schema = new Schema({
	year_timestamp: {type: String},
	deviceID: {type: String, required: true},
	name: {type: String, required: true},
	results: {
		month: {
			'1': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'2': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'3': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'4': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'5': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'6': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'7': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'8': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'9': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'10': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'11': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			},
			'12': {
				day: {
					'1': {type: Array, default: []},
					'2': {type: Array, default: []},
					'3': {type: Array, default: []},
					'4': {type: Array, default: []},
					'5': {type: Array, default: []},
					'6': {type: Array, default: []},
					'7': {type: Array, default: []},
					'8': {type: Array, default: []},
					'9': {type: Array, default: []},
					'10': {type: Array, default: []},
					'11': {type: Array, default: []},
					'12': {type: Array, default: []},
					'13': {type: Array, default: []},
					'14': {type: Array, default: []},
					'15': {type: Array, default: []},
					'16': {type: Array, default: []},
					'17': {type: Array, default: []}, 
					'18': {type: Array, default: []},
					'19': {type: Array, default: []},
					'20': {type: Array, default: []},
					'21': {type: Array, default: []},
					'22': {type: Array, default: []},
					'23': {type: Array, default: []},
					'24': {type: Array, default: []},
					'25': {type: Array, default: []},
					'26': {type: Array, default: []},
					'27': {type: Array, default: []},
					'28': {type: Array, default: []},
					'29': {type: Array, default: []},
					'30': {type: Array, default: []},
					'31': {type: Array, default: []}
				}
			}
		}
	}
});


//Creating the model
const database_data = mongoose.model('DevicesData', data_model_schema);

module.exports = database_data;